SELECT TOP (1000) [Id]
      ,[PassangerCapacity]
      ,[PricePerKilometer]
      ,[TypeId]
      ,[CategoryId]
  FROM [Agency].[dbo].[Vehicles]

SELECT TOP (1000) [Id]
      ,[VehicleId]
      ,[HasFreeFood]
  FROM [Agency].[dbo].[Airplanes]

  SELECT TOP (1000) [Id]
      ,[VehicleId]
  FROM [Agency].[dbo].[Buses]

  SELECT TOP (1000) [Id]
      ,[VehicleId]
      ,[CartsAmount]
  FROM [Agency].[dbo].[Trains]

  SELECT TOP (1000) [Id]
      ,[StartLocation]
      ,[Destination]
      ,[Distance]
      ,[TravelCosts]
      ,[VehicleId]
      ,[CategoryId]
  FROM [Agency].[dbo].[Journeys]

  SELECT TOP (1000) [Id]
      ,[JourneyId]
      ,[AdministrativeCosts]
      ,[Price]
      ,[CategoryId]
  FROM [Agency].[dbo].[Tickets]
  
  SELECT TOP (1000) [Id]
      ,[Name]
  FROM [Agency].[dbo].[Categories]

  SELECT TOP (1000) [Id]
      ,[Type]
  FROM [Agency].[dbo].[VehicleType]
